### PR TITLE
Resolve bugs in goTo function

### LINKED ISSUE #82: error in goto
there is an error in Go to ... not going to the date indicated from week

### LINKED ISSUE #271: Bug (?): "Go to..." sends you to week before selected one
Today is November 20th, when selecting Go to... Monday 4 December, I get displayed the week of Monday 27 November (the preceding week). When at that point I slide to the right to move to the next week, it doesn't display the week of Dec 4, but the week of Dec 11.
This issue only seems to be present when first day of the week is Monday (by system default or manual selection). Some testing with 'start of week' on Saturday and Sunday seems to not give any issues.

View: week view
Start of the week: Monday
Build: 1.0.12
Device: Fairphone 2
OS: Fairphone OS 17.11.2 (Android 6.0.1)

### LINKED ISSUE #642: [Bug] Using goto in daily view results makes events invisible
## Bug Explanation

When using goto to directly jump to a specific dates, all events are invisible. They will only show up after scrolling away and scrolling back to the date again.

**This only happens in "Day" view!**

## Reproduction
1. Create an event at _>date<_
2. Switch to daily view and move away from _>date<_
3. Use "Goto..." to jump to _>date<_

:warning: **Notice how no event is shown even though you created one in step 1.**

4. Now scroll a few days back and scroll back to _>date<_

:warning: **Notice how your event shows up again.**

## Demonstration
etar_daily_view_bug2

### PR DESCRIPTION
**Pull request by Gitsaibot**
Fix #642, Fix #271, Fix #82

### CODE REVIEW

File: src/com/android/calendar/AllInOneActivity.java [hunk 1]
```diff
@@ -879,14 +883,28 @@ public boolean onOptionsItemSelected(MenuItem item) {
...
+                        selectedTime.weekDay = weekday-1;
+                    }
+
                     long extras = CalendarController.EXTRA_GOTO_TIME | CalendarController.EXTRA_GOTO_DATE;
                     mController.sendEvent(this, EventType.GO_TO, selectedTime, null, selectedTime, -1, ViewType.CURRENT, extras, null, null);
                 }
             };
             DatePickerDialog datePickerDialog = new DatePickerDialog(this,datePickerListener,t.year, t.month,t.monthDay);
+            if (Build.VERSION.SDK_INT >= 21) {
+                datePickerDialog.getDatePicker().setFirstDayOfWeek(Utils.getFirstDayOfWeekAsCalendar(this));
```
Comment (jspricke) [inline src/com/android/calendar/AllInOneActivity.java:906]: why is this needed?

**Review by jspricke — APPROVED** [review]

File: src/com/android/calendar/AllInOneActivity.java (hunk 1 above)
Comment (Gitsaibot) [reply src/com/android/calendar/AllInOneActivity.java:906]: If you set the start day of the week to e.g. Saturday, the DatePicker dialog will also start on Saturday. Without this setting the DatePickerDialog will always show Monday. See https://stackoverflow.com/questions/53680906/how-to-change-start-day-of-week-of-datepickerdialog

**Comment by keunes** [comment]
Thank you!
