### PR TITLE
Fix recurring events with unsupported rrules.

### LINKED ISSUE #1132: BUG: yearly recurring event on last sunday of month X is shown every sunday
I'm using Nextcloud Calendar with the sync client DAVx on my andorid devices and Etar. I have two events in my calandar, that should remind me of the clock change for the daylight saving time.

Etar shows the events on every sunday in march/october, not only on the last sunday as intended. It works fine in the WebUI of Nextcloud Calendar, Thunderbird Calendar and Samsung Calendar.

### last sunday every march
```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//IDN nextcloud.com//Calendar app 2.1.2//EN
CALSCALE:GREGORIAN
BEGIN:VEVENT
CREATED:20201025T160620Z
DTSTAMP:20201025T160822Z
LAST-MODIFIED:20201025T160822Z
SEQUENCE:2
UID:3b52ba5b-954d-4f83-a902-e43d1ab53cd7
DTSTART;VALUE=DATE:20200329
DTEND;VALUE=DATE:20200330
SUMMARY:Zeitumstellung 2:00 auf 3:00
DESCRIPTION:Umstellung von Winterzeit auf Sommerzeit. Jedes Jahr am letzten
  Wochenende des März (in der Nacht von Samstag auf Sonntag).
TRANSP:TRANSPARENT
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=SU;BYSETPOS=-1
END:VEVENT
END:VCALENDAR
```
grafik

### last sunday every october
```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//IDN nextcloud.com//Calendar app 2.1.2//EN
CALSCALE:GREGORIAN
BEGIN:VEVENT
CREATED:20201025T155842Z
DTSTAMP:20201025T160421Z
LAST-MODIFIED:20201025T160421Z
SEQUENCE:2
UID:40d997d7-0729-4381-b993-5eec31ef70b9
DTSTART;VALUE=DATE:20201025
DTEND;VALUE=DATE:20201026
SUMMARY:Zeitumstellung 3:00 auf 2:00
DESCRIPTION:Umstellung von Sommerzeit auf Winterzeit. Jedes Jahr am letzten
  Wochenende des Oktobers (in der Nacht von Samstag auf Sonntag)
TRANSP:TRANSPARENT
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=SU;BYSETPOS=-1
END:VEVENT
END:VCALENDAR
```
grafik

### PR DESCRIPTION
**Pull request by toolstack**
The android calendar provider does not support RRULE's with BYSETPOS or BYWEEKNO properly, so additional processing has to be done to ensure that duplicate events are not added to the calendar.

This is accomplished by using a separate RRULE processor, [lib-recur](https://github.com/dmfs/lib-recur), to double check that the instance is valid.

Resolves #1132

### CODE REVIEW

File: app/src/main/java/com/android/calendar/Event.java [hunk 1]
```diff
@@ -376,6 +399,56 @@ private static Event generateEventFromCursor(Cursor cEvents, Context context) {
...
+        // We'll use SimpleDateFormat to get the D/M/Y but we also need to set the timezone.
+        SimpleDateFormat sdf = new java.text.SimpleDateFormat();
+        sdf.setTimeZone(java.util.TimeZone.getTimeZone("GMT"));
+
+        sdf.applyPattern("yyyy");
+        int startYear = Integer.parseInt(sdf.format(date));
+        sdf.applyPattern("MM");
+        int startMonth = Integer.parseInt(sdf.format(date)) - 1;
+        sdf.applyPattern("dd");
+        int startDay = Integer.parseInt(sdf.format(date));
```
Comment (tchernobog) [inline app/src/main/java/com/android/calendar/Event.java:422]: Wouldn't it be preferrable to use `java.time.LocalDateTime` instead and work with epoch, since you have no associated timezone?

Untested and uncompiled:

```java
long firstInstance = LocalDateTime
    .ofEpochSecond(startTime / 1000, (startTime % 1000) * 1000000)
    .toLocalDate() // clamping to day start
    .toInstant()
    .toEpochMillis();

// comparison:
if (instance.getTimestamp() != firstInstance) {
   return 0;
} // etc.
```

Comment (toolstack) [reply app/src/main/java/com/android/calendar/Event.java:422]: It needs to resolve out to a ```DateTime``` object to pass into ```RecurrenceSet()```, so I could work with epoch's in some of the code, but in the end it still needs to be a ```DateTime``` object, so no real point in doing both.

File: app/src/main/java/com/android/calendar/Event.java [hunk 2]
```diff
@@ -376,6 +399,56 @@ private static Event generateEventFromCursor(Cursor cEvents, Context context) {
...
+     *  In this case we're using lib-recur from https://github.com/dmfs/lib-recur through maven.
+     *
+     **/
+    static int checkRRuleEventDate( String rrule, long startTime, int endDay) {
+        // Convert the startTime into some useable Day/Month/Year values.
+        Date date = new java.util.Date(startTime);
+
+        // We'll use SimpleDateFormat to get the D/M/Y but we also need to set the timezone.
+        SimpleDateFormat sdf = new java.text.SimpleDateFormat();
+        sdf.setTimeZone(java.util.TimeZone.getTimeZone("GMT"));
```
Comment (jspricke) [inline app/src/main/java/com/android/calendar/Event.java:415]: is GMT always correct?

Comment (toolstack) [reply app/src/main/java/com/android/calendar/Event.java:415]: We're comparing against ```startTime```, which appears to always be UTC/GMT, then displayed/converted to the appropriate timezone later.

Comment (jspricke) [reply app/src/main/java/com/android/calendar/Event.java:415]: makes sense, thx!

File: app/src/main/java/com/android/calendar/Event.java [hunk 3]
```diff
@@ -376,6 +399,56 @@ private static Event generateEventFromCursor(Cursor cEvents, Context context) {
         return e;
     }
 
+    /** Android's RRULE code is broken in a way the creates additional events in certain
+     *  circumstances (though never doesn't create the actaul event) so let's use another RRULE
```
Comment (Gitsaibot) [inline app/src/main/java/com/android/calendar/Event.java:403]: nit: actual not actaul

Comment (Gitsaibot) [reply app/src/main/java/com/android/calendar/Event.java:403]: Can you fix so I can merge?

Comment (toolstack) [reply app/src/main/java/com/android/calendar/Event.java:403]: Will do.

Comment (toolstack) [reply app/src/main/java/com/android/calendar/Event.java]: Done.

**Review by Gitsaibot — APPROVED** [review]
