### PR TITLE
CalendarEventModel: Mark getCalendarEventColors method as nullable

### LINKED ISSUE #1271: NullPointerException on trying to create new event
## Summary

The `getCalendarEventColors()` method used by https://github.com/Etar-Group/Etar-Calendar/commit/2b94d7f4c745db772265d4525c443722e95ee25b is Nullable and is causing a crash when trying to create new events. This has been noticed on [CalyxOS#1361](https://gitlab.com/CalyxOS/calyxos/-/issues/1361), and is also noticeable on new installs of Etar builds compiled from the default branch.

## Stacktrace

```
2022-12-04 13:26:51.335 32727-32727/ws.xsoh.etar.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ws.xsoh.etar.debug, PID: 32727
    java.lang.NullPointerException: Attempt to get length of null array
        at java.util.Arrays.stream(Arrays.java:5575)
        at com.android.calendar.event.EditEventView.onItemSelected(EditEventView.java:1488)
        at android.widget.AdapterView.fireOnSelected(AdapterView.java:957)
        at android.widget.AdapterView.dispatchOnItemSelected(AdapterView.java:946)
        at android.widget.AdapterView.-$$Nest$mdispatchOnItemSelected(Unknown Source:0)
        at android.widget.AdapterView$SelectionNotifier.run(AdapterView.java:910)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

## Possible Fixes

Add a null check before using the method and mark the method as `@Nullable`.

### PR DESCRIPTION
**Pull request by theimpulson**
## Summary

This fixes #1271

## Test

Install a build with this patch. Ensure Etar no longer crashes on trying to create a new event.

### CODE REVIEW

File: app/src/main/java/com/android/calendar/event/EditEventView.java [hunk 1]
```diff
@@ -1485,12 +1485,14 @@ public void onItemSelected(AdapterView<?> parent, View view, int position, long
...
-                .filter(color -> color == mModel.getEventColor())
-                .findFirst()
-                .orElse(mModel.getCalendarColor()));
+        if (mModel.getCalendarEventColors() != null) {
+            mModel.setEventColor(Arrays.stream(mModel.getCalendarEventColors())
+                    .filter(color -> color == mModel.getEventColor())
+                    .findFirst()
+                    .orElse(mModel.getCalendarColor()));
+            setColorPickerButtonStates(mModel.getCalendarEventColors());
+        }
```
Comment (mikeNG) [inline app/src/main/java/com/android/calendar/event/EditEventView.java:1494]: Maybe add
```
else {
    mModel.setEventColor(mModel.getCalendarColor());
}
```
here to match old behaviour?

Comment (theimpulson) [reply app/src/main/java/com/android/calendar/event/EditEventView.java:1496]: Done

File: app/src/main/java/com/android/calendar/event/EditEventView.java [hunk 2]
```diff
@@ -1485,12 +1485,16 @@ public void onItemSelected(AdapterView<?> parent, View view, int position, long
...
-        mModel.setEventColor(Arrays.stream(mModel.getCalendarEventColors())
-                .filter(color -> color == mModel.getEventColor())
-                .findFirst()
-                .orElse(mModel.getCalendarColor()));
+        if (mModel.getCalendarEventColors() != null) {
+            mModel.setEventColor(Arrays.stream(mModel.getCalendarEventColors())
+                    .filter(color -> color == mModel.getEventColor())
+                    .findFirst()
+                    .orElse(mModel.getCalendarColor()));
+            setColorPickerButtonStates(mModel.getCalendarEventColors());
```
Comment (jonas-haeusler) [inline app/src/main/java/com/android/calendar/event/EditEventView.java:1493]: move this out of the if-block so the color picker gets disabled for calendars without colors.

Comment (mikeNG) [reply app/src/main/java/com/android/calendar/event/EditEventView.java:1493]: Wasn't the problem here that getCalendarEventColors() can return null? So it wouldn't make much sense to move it

**Comment by jonas-haeusler** [comment]
look good to me otherwise.

i dont have any calendars without color, thats why i didn't hit this case. thanks for the fix!

File: app/src/main/java/com/android/calendar/event/EditEventView.java (hunk 2 above)
Comment (jonas-haeusler) [reply app/src/main/java/com/android/calendar/event/EditEventView.java:1493]: `setColorPickerButtonStates()` checks for null and disables the color picker if necassary

```java
public void setColorPickerButtonStates(int[] colorArray) {
        setColorPickerButtonStates(colorArray != null && colorArray.length > 0);
}
```

Comment (theimpulson) [reply app/src/main/java/com/android/calendar/event/EditEventView.java]: Done

**Review by Gitsaibot — APPROVED** [review]
