### PR TITLE
Fix Event date picker for end date always preselects start

### LINKED ISSUE #1923: Event date picker for end date always preselects start date
### Description

If the start and end date of an event differ, the date picker will always preselect the start date even when opening the date picker for the end date.

#### Steps to reproduce

1. Create a new event with an end date set after the start date, e.g. start: 13.8.25, end: 20.8.25.
2. Tap on the end date.
3. The date in the date picker will be set to the start date (here 13.8.25).

<details>

<summary>example (screenshots)</summary>

Image
Image

</details>

#### Expected behavior

The date picker preselects the end date when tapping on the end date.

### App version

Latest commit [b428755](https://github.com/Etar-Group/Etar-Calendar/commit/b428755a98ddd03e7ed87d3645faaa2486e03bf4) (1.0.50)

### Android version

Android 16 (GrapheneOS)

### Device

Google Pixel 6a

### PR DESCRIPTION
**Pull request by Gitsaibot**
Fix #1923

### CODE REVIEW

File: app/src/main/java/com/android/calendar/event/EditEventView.java [hunk 1]
```diff
@@ -1669,8 +1669,14 @@ private void showDatePickerDialog(View view) {
                 .setFirstDayOfWeek(Utils.getFirstDayOfWeekAsCalendar(mActivity))
                 .build();
 
+        Calendar calStartTime = Calendar.getInstance(TimeZone.getTimeZone("UTC"));
+        calStartTime.set(mStartTime.getYear(), mStartTime.getMonth(), mStartTime.getDay());
+
+        Calendar calEndTime = Calendar.getInstance(TimeZone.getTimeZone("UTC"));
+        calEndTime.set(mEndTime.getYear(), mEndTime.getMonth(), mEndTime.getDay());
+
```
Comment (jspricke) [inline app/src/main/java/com/android/calendar/event/EditEventView.java:1677]:
```suggestion
        Calendar calPickTime = Calendar.getInstance(TimeZone.getTimeZone("UTC"));
        if (view == mStartDateButton) {
                calPickTime.set(mStartTime.getYear(), mStartTime.getMonth(), mStartTime.getDay());
        } else {
                calPickTime.set(mEndTime.getYear(), mEndTime.getMonth(), mEndTime.getDay());
        }

```

File: app/src/main/java/com/android/calendar/event/EditEventView.java [hunk 2]
```diff
@@ -1669,8 +1669,14 @@ private void showDatePickerDialog(View view) {
...
         MaterialDatePicker<Long> datePickerDialog = MaterialDatePicker.Builder.datePicker()
-                .setSelection(mStartTime.toMillis())
+                .setSelection((view == mStartDateButton) ? calStartTime.getTimeInMillis(): calEndTime.getTimeInMillis())
```
Comment (jspricke) [inline app/src/main/java/com/android/calendar/event/EditEventView.java:1679]:
```suggestion
                .setSelection(calPickTime.getTimeInMillis())
```
