### PR TITLE
Start service as "foreground service"

### LINKED ISSUE #439: A lot of java.lang.IllegalStateExceptions since 1.0.14
**java.lang.RuntimeException:** 

> at android.app.ActivityThread.handleReceiver (ActivityThread.java:3230)
at android.app.ActivityThread.-wrap17 (Unknown Source)
at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1698)
at android.os.Handler.dispatchMessage (Handler.java:106)
at android.os.Looper.loop (Looper.java:176)
at android.app.ActivityThread.main (ActivityThread.java:6635)
at java.lang.reflect.Method.invoke (Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:547)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:823)

**Caused by: java.lang.IllegalStateException:** 

> at android.app.ContextImpl.startServiceCommon (ContextImpl.java:1531)
at android.app.ContextImpl.startService (ContextImpl.java:1487)
at android.content.ContextWrapper.startService (ContextWrapper.java:660)
at android.content.ContextWrapper.startService (ContextWrapper.java:660)
at com.android.calendar.alerts.AlertReceiver.beginStartingService (AlertReceiver.java:137)
at com.android.calendar.alerts.AlertReceiver.onReceive (AlertReceiver.java:840)
at android.app.ActivityThread.handleReceiver (ActivityThread.java:3223)

### PR DESCRIPTION
**Pull request by Gitsaibot**
Start service as "foreground service". Fix #439 #445 #497

### CODE REVIEW

File: src/com/android/calendar/alerts/AlertService.java [hunk 1]
```diff
@@ -980,6 +981,16 @@ public void onCreate() {
     @Override
     public int onStartCommand(Intent intent, int flags, int startId) {
         if (intent != null) {
+
+            if (Utils.isOreoOrLater()) {
+                Notification notification = new NotificationCompat.Builder(this, ALERT_CHANNEL_ID)
+                        .setContentTitle("Update alerts")
```
Comment (jspricke) [inline src/com/android/calendar/alerts/AlertService.java]: maybe change this to "Event notifications"?
